'use client';
import { useMemo, useState } from 'react';

const upcoming = [
  { code:'301699',name:'洛轴股份',board:'创业板',date:'08-26',price:'15.88',score:80,heat:82,odds:'申购后公布',profit:'待上市估算',tone:'good',label:'重点关注',pe:'22.67×',cap:'1.45万股',analysis:'发行市盈率22.67倍，低于行业38.35倍及可比公司均值27.03倍；但战略配售占发行量40%，仍需关注上市流通结构。' },
  { code:'603448',name:'天博智能',board:'沪市主板',date:'08-26',price:'62.65',score:76,heat:75,odds:'申购后公布',profit:'待上市估算',tone:'good',label:'可以申购',pe:'16.07×',cap:'0.95万股',analysis:'发行市盈率16.07倍，低于行业22.82倍；发行价较高，单签缴款约3.13万元，需为中签缴款预留资金。' },
  { code:'920269',name:'杰锋动力',board:'北交所',date:'08-26',price:'30.70',score:65,heat:63,odds:'比例配售',profit:'待上市估算',tone:'warn',label:'谨慎申购',pe:'12.98×',cap:'44.49万股',analysis:'北交所资金申购、比例配售，发行后市盈率约12.98倍；顶格资金需求很高，更应比较预期配售率与资金占用效率。' },
  { code:'301689',name:'电科思仪',board:'创业板',date:'08-28',price:'待定',score:70,heat:71,odds:'申购后公布',profit:'待定价',tone:'warn',label:'等待定价',pe:'待定',cap:'1.20万股',analysis:'申购日为8月28日，目前发行价及发行市盈率尚未正式确定；评分仅为占位，定价公告后需要重新计算估值与收益区间。' },
];
const history = [
  { name:'嘉立创',board:'深市主板',price:84.46,pe:38.19,rate:0.02185,first:126,score:86 },
  { name:'津富士达',board:'沪市主板',price:17.46,pe:19.25,rate:0.02418,first:64,score:79 },
  { name:'展芯股份',board:'创业板',price:23.45,pe:44.23,rate:0.01596,first:48,score:72 },
  { name:'欣兴工具',board:'创业板',price:33.58,pe:17.17,rate:0.01466,first:91,score:83 },
  { name:'维通利',board:'深市主板',price:30.38,pe:25.36,rate:0.0207,first:37,score:68 },
];
function MiniLine(){return <svg viewBox="0 0 520 150" role="img" aria-label="近十二月新股首日收益趋势" className="chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff6b3d" stopOpacity=".28"/><stop offset="1" stopColor="#ff6b3d" stopOpacity="0"/></linearGradient></defs><path d="M5 115 C42 94 56 106 91 83 S143 101 177 70 S228 52 260 75 S306 42 344 58 S395 31 430 44 S478 18 515 28 L515 145 L5 145Z" fill="url(#area)"/><path d="M5 115 C42 94 56 106 91 83 S143 101 177 70 S228 52 260 75 S306 42 344 58 S395 31 430 44 S478 18 515 28" fill="none" stroke="#ff6b3d" strokeWidth="4" strokeLinecap="round"/></svg>}

export default function Home(){
  const [board,setBoard]=useState('全部'); const [selected,setSelected]=useState(upcoming[0]);
  const filtered=useMemo(()=>board==='全部'?history:history.filter(x=>x.board.includes(board)),[board]);
  return <main>
    <nav><div className="brand"><span className="mark">新</span><span>新股雷达</span><em>Beta</em></div><div className="navlinks"><a className="active">今日机会</a><a href="#history">历史表现</a><a href="#model">评分模型</a></div><button className="outline">设置提醒 <span>→</span></button></nav>
    <div className="ticker"><span>本周申购</span><strong>4只</strong><i/><span>8月26日</span><strong>3只</strong><span>8月28日</span><strong className="orange">1只</strong><small>日历更新至 2026-08-25 12:00</small></div>
    <section className="hero"><div><p className="eyebrow">A股打新决策助手</p><h1>别凭感觉打新，<br/><span>让历史数据给答案。</span></h1><p className="lede">综合发行估值、市场热度、公司质量与历史相似新股，给出更清晰的申购判断。</p></div><div className="market-card"><div className="card-top"><div><span className="live-dot"/>本周申购日历</div><strong>已更新至今天</strong></div><div className="gauge"><div><b>4</b><small>只</small></div></div><div className="signal-row"><span>明日申购<strong>3只</strong></span><span>周五申购<strong>1只</strong></span><span>下次更新<strong className="low">定价公告后</strong></span></div></div></section>
    <section className="content"><div className="section-title"><div><p className="eyebrow">即将申购 · 8月25日更新</p><h2>本周值得关注</h2></div><button className="ghost">查看完整日历 →</button></div><div className="ipo-grid">{upcoming.map(x=><button key={x.code} className={`ipo-card ${selected.code===x.code?'selected':''}`} onClick={()=>setSelected(x)}><div className="ipo-head"><span className="date"><b>{x.date}</b><small>申购</small></span><div><h3>{x.name}</h3><p>{x.code} · {x.board}</p></div><span className={`badge ${x.tone}`}>{x.label}</span></div><div className="score"><span style={{'--score':`${x.score}%`} as React.CSSProperties}/><b>{x.score}</b><small>当前初评</small></div><div className="metrics"><span>发行价<b>{x.price==='待定'?x.price:`¥${x.price}`}</b></span><span>发行PE / 上限<b>{x.pe} · {x.cap}</b></span><span>中签方式<b className="profit">{x.odds}</b></span></div><div className="reasons"><span>热度初评 {x.heat}</span><span>数据截至 08-25</span><span>{x.price==='待定'?'等待定价':'价格已确定'}</span></div></button>)}</div><div className="detail-strip"><div><span className="pill">当前解读</span><strong>{selected.name}</strong>：{selected.analysis}</div><button>查看完整分析</button></div></section>
    <section className="history" id="history"><div className="section-title"><div><p className="eyebrow">历史数据实验室</p><h2>过去表现，检验今天的判断</h2></div><div className="filters">{['全部','主板','创业板'].map(x=><button className={board===x?'on':''} onClick={()=>setBoard(x)} key={x}>{x}</button>)}</div></div><div className="history-grid"><div className="trend-card"><div className="trend-head"><div><p>近12月新股首日平均收益</p><h3>+68.4% <small>环比 +12.7%</small></h3></div><span className="legend">● 首日涨幅</span></div><MiniLine/><div className="months"><span>9月</span><span>11月</span><span>1月</span><span>3月</span><span>5月</span><span>7月</span></div></div><div className="stats"><div><span>模型建议申购胜率</span><b>82.6%</b><small>历史样本回测</small></div><div><span>近20只破发率</span><b>15.0%</b><small className="goodtext">处于低位</small></div><div><span>平均中签率</span><b>0.019%</b><small>沪深网上发行</small></div><div><span>平均单签浮盈</span><b>¥7,240</b><small>按首日收盘估算</small></div></div></div><div className="table-card"><table><thead><tr><th>新股</th><th>板块</th><th>发行价</th><th>发行PE</th><th>中签率</th><th>首日涨幅</th><th>模型评分</th></tr></thead><tbody>{filtered.map(x=><tr key={x.name}><td><strong>{x.name}</strong></td><td>{x.board}</td><td>¥{x.price}</td><td>{x.pe}×</td><td>{x.rate}%</td><td className="up">+{x.first}%</td><td><span className="score-tag">{x.score}</span></td></tr>)}</tbody></table><p className="source">来源：交易所及巨潮资讯公开发行数据；首日涨幅、回测指标为第一版演示字段，请以上线后的正式数据管道为准。</p></div></section>
    <section className="model" id="model"><p className="eyebrow">评分方法</p><h2>五个维度，不做黑箱结论</h2><div className="model-grid">{[['30%','发行估值','行业与可比公司折溢价'],['20%','市场环境','近期新股涨幅与破发率'],['20%','公司质量','成长、盈利与现金流'],['15%','行业热度','板块趋势与成交热度'],['15%','发行结构','流通盘、募资与战略配售']].map((x,i)=><div key={x[1]}><span>0{i+1}</span><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
    <footer><div className="brand"><span className="mark">新</span><span>新股雷达</span></div><p>数据辅助判断，不构成投资建议。投资有风险，申购需谨慎。</p><span>© 2026 新股雷达</span></footer>
  </main>
}
